### ISSUE TITLE
Clarify "LGPL v2" dual-licensing

### ISSUE THREAD

**Issue by Mno-hime** [B00merang-Project/Solaris-11#1]
From https://github.com/B00merang-Project/Solaris-11/commit/b8f82dde4131da04a9879158fbea99dd35f277c4 I understood that the second license is "LGPL v2", from the link after it seems to mean "Licence publique générale GNU pour les **bibliothèques**, version 2.0" ("GNU **Library** General Public License, version 2.0" in English). Note that this is the old and now uncommon variant of the "lesser" GPL 2.

I was wondering if this was you intention? Maybe you meant "GNU **Lesser** General Public License, version 2.1" (https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html), the newer variant of "lesser" GPL 2.

In any case, thank you very much for dual-licensing you work. At OpenIndiana we very much appreciate it!

**Comment by Elbullazul** [comment]
oops, my mistake. I'll fix the link, thanks for pointing this out!

**Comment by Elbullazul** [comment]
5f5d454 fixes this
