### ISSUE TITLE
Original Minimize, Maximize, and Close buttons

### ISSUE THREAD

**Issue by eturkes** [B00merang-Project/Solaris-11#2]
This is awesome, but would you consider making a version with Minimize, Maximize, and Close buttons more similar to the original? These contain a different symbol inside the squares and I prefer the originals. If you cannot change them, any hints on how I can modify them myself? I'm using Gnome Shell. Thanks!

**Comment by Elbullazul** [comment]
I'll try

**Comment by Elbullazul** [comment]
a49b15a adds original buttons and migrates the codebase to the Azurra framework
